[build]
    publish = "."

    command = "echo 'I be building' "

    functions = "src/router"

[[redirects]]
    from = "/*"
    to   = "/:splat"
    status = 200

[[redirects]]
    from = "/*"
    to   = "asistencia.html"
    status = 200

[[redirects]]
    from = "/index.js"
    to   = "404.html"


[[redirects]]
    from = "/src/*"
    to   = "404.html"
    status = 404


[[redirects]]
    from = "/src/scripts/*"
    to   = "404.html"
    status = 404


[[redirects]]
    from = "/src/scripts/index.js"
    to   = "404.html"
    status = 404