[build]
    publish = "."

    command = "echo 'I be building' "

    functions = "src/router"

[[redirects]]
    from = "/*"
    to   = "/:splat"
    status = 200

[[redirects]]
    from = "/*"
    to   = "asistencia.html"
    status = 200